#### COMPANION WORKBOOK

# NumPy

To make the most out this program, we strongly recommend you to:
1. First practice writing and implementing all of the code from Coding Section of the online lesson.
2. Then, freely experiment with and explore any interesting or confusing concepts. Simply insert new code cells and then use the help of Google and official documentation.
3. Finally, tackle all of the exercises at the end. They will help you tie everything together and **learn in context.**

#### <span style="color:#555">LESSON CODE SANDBOX</span>

Use this space to practice writing and implementing all of the code from Coding Section of the online lesson. Insert new code cells as needed, and feel free to write notes to yourself in Markdown.

First, let's import the actual NumPy library.

In [106]:
import numpy as np

## I. NumPy Arrays are homogeneous.

In [107]:
array_a = np.array([1,2,3,4])

print(array_a)

print(type(array_a))


[1 2 3 4]
<class 'numpy.ndarray'>


In [108]:
print(array_a.dtype)

int64


In [109]:
# numpy arrays are homogenous

array_b = np.array(['five', 7, 3])

print(array_b)

['five' '7' '3']


In [110]:
# Shape & Axes

print(array_a.shape)
print(array_b.shape)

(4,)
(3,)


In [111]:
# indexing array

array_a[0]

array_a[-1]

4

In [112]:
#Slicing numpy array

print(array_a[2:4])

[3 4]


In [113]:
# NaN & Missing Data

array_with_missing_values = np.array([4.0,5,9, np.nan, 10])

print(array_with_missing_values)

[ 4.  5.  9. nan 10.]


In [114]:
# check the array data type

print(array_with_missing_values.dtype)

float64


## II. NumPy Arrays are multidimensional.

In [115]:
# create a 2 x 3 array

array_c = np.array([[2,4,9],[1,3,9]])

print(array_c)

print(array_c.shape)

[[2 4 9]
 [1 3 9]]
(2, 3)


In [116]:
# reshaping array to 3 x 2

print(array_c.reshape(3, 2))



[[2 4]
 [9 1]
 [3 9]]


In [117]:
# reshape array to 6 x 1

print(array_c.reshape(6, 1))

[[2]
 [4]
 [9]
 [1]
 [3]
 [9]]


In [120]:
# reshape to 1 x 6

print(array_c.reshape(1, 6))

[[2 4 9 1 3 9]]


In [121]:
# reshape to 2 x 4

print(array_c.reshape(2, 4))

ValueError: cannot reshape array of size 6 into shape (2,4)

In [122]:
# Flattening an array
print(array_c.flatten())

[2 4 9 1 3 9]


In [123]:
# Transposing arrays

print(array_c.transpose())

[[2 1]
 [4 3]
 [9 9]]


In [124]:
# create a 3 x 3 array

array_d = np.array(range(1,10)).reshape(3,3)
print(array_d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [125]:
# select first row

print(array_d[0, :])

[1 2 3]


In [126]:
# select second row

print(array_d[1, :])

[4 5 6]


In [127]:
# select second column

print(array_d[: , 1])

[2 5 8]


In [128]:
# select third column 

print(array_d[: , 2])

[3 6 9]


In [129]:
# select  from second row to the last
print(array_d[1:,])

[[4 5 6]
 [7 8 9]]


In [130]:
# select  from second row to the last and select from second column to the last
print(array_d[1:, 1:])

[[5 6]
 [8 9]]


In [131]:
# select from first row to the last and select from second column to the last
print(array_d[0:, 1:])

[[2 3]
 [5 6]
 [8 9]]


## III. NumPy math is elementwise.

In [132]:
# 2 x 2 float matrix

x = np.array([[2.1,3.0], [4.9,5.2]])

y = np.array([[3.2, 5.0],[2.8, 2.1]])


print(x)
print(y)

[[2.1 3. ]
 [4.9 5.2]]
[[3.2 5. ]
 [2.8 2.1]]


In [133]:
# Addition 

print( x + y)

[[5.3 8. ]
 [7.7 7.3]]


In [134]:
# subtraction

print('Subtraction => {}'.format(x - y), '\n')

# multiplication

print('Multiplication => {}'.format(x * y), '\n')

# division

print('Division => {}'.format(x / y), '\n')

# modulo

print('Modulo => {}'.format(x % y), '\n')

Subtraction => [[-1.1 -2. ]
 [ 2.1  3.1]] 

Multiplication => [[ 6.72 15.  ]
 [13.72 10.92]] 

Division => [[0.65625    0.6       ]
 [1.75       2.47619048]] 

Modulo => [[2.1 3. ]
 [2.1 1. ]] 



In [135]:
# single array and scalar operations

print( x + 2)

[[4.1 5. ]
 [6.9 7.2]]


In [136]:
# subtraction

print('single array and scalar operations Subtraction => {}'.format(x - 2), '\n')

# multiplication

print('single array and scalar operations Multiplication => {}'.format(x * 2), '\n')

# division

print('single array and scalar operations Division => {}'.format(x / 2), '\n')

# modulo

print('single array and scalar operations Modulo => {}'.format(x % 2), '\n')

single array and scalar operations Subtraction => [[0.1 1. ]
 [2.9 3.2]] 

single array and scalar operations Multiplication => [[ 4.2  6. ]
 [ 9.8 10.4]] 

single array and scalar operations Division => [[1.05 1.5 ]
 [2.45 2.6 ]] 

single array and scalar operations Modulo => [[0.1 1. ]
 [0.9 1.2]] 



In [137]:
# numpy built in raised to power 2
print(np.power(x, 2), '\n')


# numpy built in raised to power 3
print(np.power(x, 3), '\n')


# numpy built in exponential
print(np.exp(x), '\n')


# numpy built in Natural log
print(np.log(x), '\n')


# numpy built in square root
print(np.sqrt(x), '\n')


[[ 4.41  9.  ]
 [24.01 27.04]] 

[[  9.261  27.   ]
 [117.649 140.608]] 

[[  8.16616991  20.08553692]
 [134.28977968 181.27224188]] 

[[0.74193734 1.09861229]
 [1.58923521 1.64865863]] 

[[1.44913767 1.73205081]
 [2.21359436 2.28035085]] 



In [138]:
# Numpy aggregation functions
x = np.array([[2.1,3.0], [4.9,5.2]])

# sum 
print(np.sum(x))

# mean
print(np.mean(x))

# max
print(np.max(x))

# min
print(np.min(x))

# median
print(np.median(x))



15.2
3.8
5.2
2.1
3.95


In [139]:
# aggregate across columns or rows

# axis = 0 is for aggregation across columns
# axis = 1 is for aggregation across rows


# sum of each column
print(np.sum(x, axis=0))

# sum of each row
print(np.sum(x, axis=1))


[7.  8.2]
[ 5.1 10.1]


In [140]:
print(np.sum)

<function sum at 0x7fa4d90a88b0>


## IV. NumPy is reliably random.

In [141]:
# Numpy random tools

np.random

# generate a 8x8 matrix of random digits from 0 to 9

# Randomly draw 64 samples from a uniform distribution from [0, 10)

# low: Lower boundary for sampling (inclusive)
# high: Upper boundary for sampling (exclusive)
# size: Number of samples to draw

samples = np.random.randint(low=0, high=10, size=64)

print(samples)

[3 8 7 1 5 7 8 3 7 0 7 2 1 8 0 8 9 8 4 5 4 9 1 8 2 0 7 2 8 0 5 6 3 8 7 2 1
 3 5 3 9 2 8 0 3 2 1 2 0 5 4 3 7 4 2 0 8 3 0 0 9 4 6 9]


In [142]:
# reshape the array into an 8 X 8 matrix


print(samples.reshape(8, 8))

[[3 8 7 1 5 7 8 3]
 [7 0 7 2 1 8 0 8]
 [9 8 4 5 4 9 1 8]
 [2 0 7 2 8 0 5 6]
 [3 8 7 2 1 3 5 3]
 [9 2 8 0 3 2 1 2]
 [0 5 4 3 7 4 2 0]
 [8 3 0 0 9 4 6 9]]


In [143]:
# Another approach 

generated_matrix = np.random.randint(0,10, (8,8))

print(generated_matrix)

[[6 5 3 5 1 7 5 9]
 [3 6 2 2 6 0 8 1]
 [7 2 9 1 0 9 1 7]
 [1 2 3 4 2 7 8 4]
 [3 2 4 4 6 6 0 2]
 [3 4 2 0 8 0 7 4]
 [0 9 6 5 4 1 1 7]
 [4 4 0 8 4 1 9 9]]


In [144]:
generated_matrix = np.random.randint(0,10, (8,8))

print(generated_matrix)

[[2 1 0 7 0 9 0 0]
 [9 3 6 8 2 8 7 1]
 [0 1 4 3 4 4 0 5]
 [9 2 4 5 9 0 8 2]
 [8 1 7 2 9 2 8 4]
 [5 1 1 2 3 0 2 5]
 [6 7 5 7 4 6 0 4]
 [9 0 0 5 4 9 0 3]]


In [145]:
# add random seed

np.random.seed(321)

generated_matrix = np.random.randint(0,10, (8,8))

print(generated_matrix)

[[4 9 8 1 8 8 4 5]
 [8 3 5 1 4 6 5 7]
 [7 2 2 3 9 2 1 2]
 [1 1 0 4 4 3 0 3]
 [7 4 5 7 0 8 7 1]
 [0 2 5 6 1 0 7 2]
 [8 3 0 3 9 8 5 6]
 [0 2 7 5 2 3 9 9]]


In [146]:
np.random.seed(321)

generated_matrix = np.random.randint(0,10, (8,8))

print(generated_matrix)

[[4 9 8 1 8 8 4 5]
 [8 3 5 1 4 6 5 7]
 [7 2 2 3 9 2 1 2]
 [1 1 0 4 4 3 0 3]
 [7 4 5 7 0 8 7 1]
 [0 2 5 6 1 0 7 2]
 [8 3 0 3 9 8 5 6]
 [0 2 7 5 2 3 9 9]]


In [147]:
# set seed for reproductilbility
np.random.seed(321)

generated_matrix = np.random.randint(0,10, (8,8))

print(generated_matrix)

[[4 9 8 1 8 8 4 5]
 [8 3 5 1 4 6 5 7]
 [7 2 2 3 9 2 1 2]
 [1 1 0 4 4 3 0 3]
 [7 4 5 7 0 8 7 1]
 [0 2 5 6 1 0 7 2]
 [8 3 0 3 9 8 5 6]
 [0 2 7 5 2 3 9 9]]


In [148]:
# randomly select element from the generated matrix
# set seed for reproductilbility
np.random.seed(55)

# random choice takes the array and the number of element to select


# Randomly select 5 elements from first column of generated_matrix
print(np.random.choice(generated_matrix[:, 0], 5))

# random.choice sampled the above with replacements

[0 7 0 4 0]


In [149]:
# random choice without replacements

#set seed for reproducibility
np.random.seed(55)


print(np.random.choice(generated_matrix[:, 0], 5, replace=False))

[7 0 8 8 1]


#### <span style="color:#555">EXERCISES</span>

Complete each of the following exercises.

## <span style="color:RoyalBlue">Exercise 4.1 - Business Park Arrays</span>

#### In the previous lesson...

In the previous lesson, we decided on Park Royal as our first stop in our training mission to London. Now we've arrived at the tube station! Park Royal is home to London's largest business park. 
* Assume the business park supports 1,700 businesses.
* HQ sent you a manual with their names and locations. 
* *They are listed in order from smallest to largest* (this will be important later).

#### A.) First, let's create a NumPy array called <code style="color:steelblue">business_ids</code>.
* The first business has ID <code>1</code>, the second one has ID <code>2</code> and so on.
* Remember that Python is zero-indexed... but your business ID array should still start from 1!
* The array should have shape <code style="color:steelblue">(1700,)</code>.

In [150]:
# Create array of business_ids with values ranging from 1 to 1700

business_ids = np.array(range(1,1701))
print(business_ids)

[   1    2    3 ... 1698 1699 1700]


#### B.) Next, print the shape of <code style="color:steelblue">business_ids</code> to confirm it has shape <code style="color:steelblue">(1700,)</code>.

In [151]:
# Print shape of business_ids
print(business_ids.shape)

(1700,)


<strong style="color:RoyalBlue">Expected output:</strong>

<pre>
(1700,)
</pre>

#### C.) Finally, print the last 10 business ID's to confirm the array is set up properly.

In [154]:
# Print last 10 business ID's
print(business_ids[-10:])

[1691 1692 1693 1694 1695 1696 1697 1698 1699 1700]


<strong style="color:RoyalBlue">Expected output:</strong>

<pre>
[1691 1692 1693 1694 1695 1696 1697 1698 1699 1700]
</pre>

## <span style="color:RoyalBlue">Exercise 4.2 - Stratified Random Sampling</span>

There are **1700** businesses in Park Royal's business park. However, you only have **10** hours to stay in Park Royal before you need to move on to the next location. Assuming you could only visit **5** businesses per hour, which businesses should you visit?

#### Well, 2 options immediately come to mind:
1. You could just visit the first 50 businesses.
2. You could randomly sample 50 businesses.

While these appear fine at first glance, there are potential flaws with both of these approaches. *Remember, we learned that the businesses were listed in order from smallest to largest! Therefore...*
1. Just visiting the first 50 would give us a biased sample of only the smallest businesses.
2. Visiting a random sample of 50 is better, but there's still a chance that our sample ends up biased from pure chance.

#### Instead, let's take a *stratified random sample* based on the size of the business.
* Stratified random sampling is a sampling method by which you first group your observations based on a **key variable**, and then randomly sampling from those groups.
* This will ensure your sample is **representative** of the broader dataset along that key variable. In other words, your sample will be "spread out" across different values of that key variable.

<p style="text-align:center">
<img src="https://upload.wikimedia.org/wikipedia/commons/f/fa/Stratified_sampling.PNG" alt="Stratified Random Sampling" style="width: 280px;"/>
<br>
<em>Stratified Random Sampling</em>
</p>

#### For this exercise, stratified random sampling just means that...
* We'll start by splitting our businesses into 10 groups of 170 businesses each.
* The first group will have ID's from 1 to 170, the second will have ID's from 171 to 340, etc.
* Then we'll randomly select 5 businesses from each group of 170.
* Since the businesses are already ordered by size, this will ensure that small, medium, and big businesses are all represented in our sample.

#### A.) First, reshape the 1-dimensional <code style="color:steelblue">business_ids</code> array into a new 2-dimensional <code style="color:steelblue">id_matrix</code> array.
* <code style="color:steelblue">id_matrix</code> should have **10 columns**... one for each group of businesses.
* How many rows should it have?
* What does the number of rows represent?

In [155]:
# Create id_matrix by reshaping business_ids to have 10 columns
id_matrix = business_ids.reshape(170,10)


# Print shape
print(id_matrix.shape)
print(id_matrix)



(170, 10)
[[   1    2    3 ...    8    9   10]
 [  11   12   13 ...   18   19   20]
 [  21   22   23 ...   28   29   30]
 ...
 [1671 1672 1673 ... 1678 1679 1680]
 [1681 1682 1683 ... 1688 1689 1690]
 [1691 1692 1693 ... 1698 1699 1700]]


<strong style="color:RoyalBlue">Expected output:</strong>

<pre>
(170, 10)
</pre>

Great, now we have a matrix with 10 columns representing 10 groups of businesses. But remember, our goal is to stratify our sample by size of the business, and because our businesses are ordered by size, the first group should be 1 to 170, the second group should be 171 to 340, and so on.

#### B.) Print the first column (group) of <code style="color:steelblue">id_matrix</code>.
* Does it contain businesses 1 to 170?

In [156]:
# Print first column of id_matrix

print(id_matrix[:,0])

[   1   11   21   31   41   51   61   71   81   91  101  111  121  131
  141  151  161  171  181  191  201  211  221  231  241  251  261  271
  281  291  301  311  321  331  341  351  361  371  381  391  401  411
  421  431  441  451  461  471  481  491  501  511  521  531  541  551
  561  571  581  591  601  611  621  631  641  651  661  671  681  691
  701  711  721  731  741  751  761  771  781  791  801  811  821  831
  841  851  861  871  881  891  901  911  921  931  941  951  961  971
  981  991 1001 1011 1021 1031 1041 1051 1061 1071 1081 1091 1101 1111
 1121 1131 1141 1151 1161 1171 1181 1191 1201 1211 1221 1231 1241 1251
 1261 1271 1281 1291 1301 1311 1321 1331 1341 1351 1361 1371 1381 1391
 1401 1411 1421 1431 1441 1451 1461 1471 1481 1491 1501 1511 1521 1531
 1541 1551 1561 1571 1581 1591 1601 1611 1621 1631 1641 1651 1661 1671
 1681 1691]


<strong style="color:RoyalBlue">Expected output:</strong>

<pre>
[   1   11   21   31   41   51   61   71   81   91  101  111  121  131  141
  151  161  171  181  191  201  211  221  231  241  251  261  271  281  291
  301  311  321  331  341  351  361  371  381  391  401  411  421  431  441
  451  461  471  481  491  501  511  521  531  541  551  561  571  581  591
  601  611  621  631  641  651  661  671  681  691  701  711  721  731  741
  751  761  771  781  791  801  811  821  831  841  851  861  871  881  891
  901  911  921  931  941  951  961  971  981  991 1001 1011 1021 1031 1041
 1051 1061 1071 1081 1091 1101 1111 1121 1131 1141 1151 1161 1171 1181 1191
 1201 1211 1221 1231 1241 1251 1261 1271 1281 1291 1301 1311 1321 1331 1341
 1351 1361 1371 1381 1391 1401 1411 1421 1431 1441 1451 1461 1471 1481 1491
 1501 1511 1521 1531 1541 1551 1561 1571 1581 1591 1601 1611 1621 1631 1641
 1651 1661 1671 1681 1691]
</pre>

Crap, that's not what we wanted. Ah, but we should have seen this coming!

Remember, when you <code style="color:steelblue">.reshape</code> an array, the new array keeps the order of the elements. Let's see how we can solve this.

## <span style="color:RoyalBlue">Exercise 4.3 - Toy Problem Interlude</span>

Let's walk through a miniature example of what we just did in the previous exercise, because it will be easier to understand by peeking under the hood. 
* Instead of 1700 businesses, let's say we only had **170** businesses to visit, but we still want to group them into **10** groups by ID.
* Therefore, we want the first group to have businesses **1 to 17**, the second group to have **18 to 34**, the third group to have **35 to 51**, and so on.

By using this type of "toy problem," we can actually print the entire matrix and see what's going on under the hood when we reshape an array.

#### A.) Create a new <code>mini_business_ids</code> array with only 170 businesses (10% of the size of our full problem).
* Then reshape it to only have 10 columns and store it as <code>mini_id_matrix</code>.
* Finally, display <code>mini_id_matrix</code>.

In [157]:
# Create array of 170 ID's
mini_business_ids = np.array(range(1,171))

# Reshape to have 10 columns
mini_id_matrix = mini_business_ids.reshape(17,10)

# Display mini_id_matrix

print(mini_id_matrix)


[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]
 [101 102 103 104 105 106 107 108 109 110]
 [111 112 113 114 115 116 117 118 119 120]
 [121 122 123 124 125 126 127 128 129 130]
 [131 132 133 134 135 136 137 138 139 140]
 [141 142 143 144 145 146 147 148 149 150]
 [151 152 153 154 155 156 157 158 159 160]
 [161 162 163 164 165 166 167 168 169 170]]


<strong style="color:RoyalBlue">Expected output:</strong>

<pre>
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]
 [101 102 103 104 105 106 107 108 109 110]
 [111 112 113 114 115 116 117 118 119 120]
 [121 122 123 124 125 126 127 128 129 130]
 [131 132 133 134 135 136 137 138 139 140]
 [141 142 143 144 145 146 147 148 149 150]
 [151 152 153 154 155 156 157 158 159 160]
 [161 162 163 164 165 166 167 168 169 170]]
</pre>

There! Do you see how it fills in the matrix one row at a time?
* So, when you select the first **column**, you're not getting businesses 1 to 17. 
* Instead, you're getting every 10th business: 1, 11, 21, 31, etc...

#### B.) Aha, now we're on to something... so instead of reshaping to 17 rows and 10 columns, let's try reshaping it to 10 rows and 17 columns.

In [158]:
# Reshape to have 10 rows
reform = mini_id_matrix.reshape(10,17)

# Display mini id matrix
print(reform)


[[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17]
 [ 18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34]
 [ 35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51]
 [ 52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68]
 [ 69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85]
 [ 86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101 102]
 [103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136]
 [137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153]
 [154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170]]


<strong style="color:RoyalBlue">Expected output:</strong>

<pre>
[[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17]
 [ 18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34]
 [ 35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51]
 [ 52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68]
 [ 69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85]
 [ 86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101 102]
 [103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136]
 [137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153]
 [154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170]]
</pre>

Now we have 10 rows instead of 10 columns. 
* The first **row** has the businesses 1 to 17, which is what we want!
* And if we want the first **column** to have businesses 1 to 17, we can simply **transpose** this matrix.

Working through toy problems is an underappreciated and very useful skill in data science... Toy problems are basically miniature versions of your problem that are easier to break apart and understand conceptually. You'll often be working with difficult datasets or solving tough analytical problems. If you get stuck, it can be helpful to work through a simpler version of the problem by reducing the size of your dataset or trying easier algorithms!

## <span style="color:RoyalBlue">Exercise 4.4 - SRS Round 2</span>

Let's try building that <code style="color:steelblue">id_matrix</code> again. 

#### A.) This time, reshape it to have 10 rows, each representing 1 group of businesses.
* The first row should contain businesses 1 to 170.

In [175]:
# Reshape business_ids to have 10 rows, with 170 businesses each

id_matrix = business_ids.reshape(10,170)


#### B.) Now, print the first *row* of <code style="color:steelblue">id_matrix</code>.

In [176]:
# Print the first row of id_matrix
print(id_matrix[0])


[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170]


<strong style="color:RoyalBlue">Expected output:</strong>

<pre>
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170]
</pre>

You should see the businesses with ID's from **1 to 170**. Now, what if we still want our groups to be grouped by column, instead of by row? Let's *flip our rows and columns* now that the rows have the correct groups.

#### C.) Overwrite <code style="color:steelblue">id_matrix</code> with its transposed version.
* After you do so, print the first column in the new <code style="color:steelblue">id_matrix</code> to confirm the group is correct.
* Also print the shape of the new <code style="color:steelblue">id_matrix</code> to confirm your new dimensions are correct.

In [177]:
# Overwrite id_matrix with flipped version

id_matrix = id_matrix.transpose()
# Print first column
print(id_matrix[:,0])

# Print shape of new id_matrix
print(id_matrix.shape)



[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170]
(170, 10)


<strong style="color:RoyalBlue">Expected output:</strong>

<pre>
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170]
(170, 10)
</pre>

## <span style="color:RoyalBlue">Exercise 4.5 - Final Business Selections</span>

Let's take another look at our <code style="color:steelblue">id_matrix</code>. 

* In <span style="color:royalblue">Exercise 4.2b</span> we displayed the first group (column) and confirmed that the ID's were from **1 to 170**.
* Now let's confirm the rest of the array is correct by finding the <code style="color:steelblue">np.min()</code> and <code style="color:steelblue">np.max()</code> of each group.

#### A.) First, create and print an object called <code style="color:steelblue">group_min</code> with the minimum ID of each group (column) of <code style="color:steelblue">id_matrix</code>.

In [210]:
# Create group_min

group_min = np.asarray([np.min(id_matrix[:, 0]), np.min(id_matrix[:, 1]), np.min(id_matrix[:, 2]),np.min(id_matrix[:, 3]),np.min(id_matrix[:, 4]),np.min(id_matrix[:, 5]),np.min(id_matrix[:, 6]),np.min(id_matrix[:, 7]),np.min(id_matrix[:, 8]),np.min(id_matrix[:, 9])])


# Print group_min
print(group_min)



[   1  171  341  511  681  851 1021 1191 1361 1531]


<strong style="color:RoyalBlue">Expected output:</strong>

<pre>
[   1  171  341  511  681  851 1021 1191 1361 1531]
</pre>

#### B.) Next, create and print an object called <code style="color:steelblue">group_max</code> with the maximum ID of each group (column) of <code style="color:steelblue">id_matrix</code>.

In [219]:
# Create group_max

group_max = np.asarray([np.max(id_matrix[:, 0]), np.max(id_matrix[:, 1]), np.max(id_matrix[:, 2]),np.max(id_matrix[:, 3]),np.max(id_matrix[:, 4]),np.max(id_matrix[:, 5]),np.max(id_matrix[:, 6]),np.max(id_matrix[:, 7]),np.max(id_matrix[:, 8]),np.max(id_matrix[:, 9])])
# Print group_max

print(group_max)



[ 170  340  510  680  850 1020 1190 1360 1530 1700]


<strong style="color:RoyalBlue">Expected output:</strong>

<pre>
[ 170  340  510  680  850 1020 1190 1360 1530 1700]
</pre>

#### C.) Next, subtract <code style="color:steelblue">group_min</code> from <code style="color:steelblue">group_max</code> to confirm that each of the 10 groups has a <span style="tomato">range</span> of 170.
* Remember to add 1 to the difference between max and min because the ends are inclusive 
    * i.e. $170 - 1 = 169$

In [232]:
# Print range of each group
grp = group_max - group_min
print(grp + 1)



[170 170 170 170 170 170 170 170 170 170]


<strong style="color:RoyalBlue">Expected output:</strong>

<pre>
[170 170 170 170 170 170 170 170 170 170]
</pre>

Great. We are now ready to select 5 businesses from each group in <code style="color:steelblue">id_matrix</code>.

#### D.) Finally, write a loop that chooses 5 businesses from column of <code style="color:steelblue">id_matrix</code>.
* Set the random seed to 123. (This is just an arbitrary seed chosen for replicable results... you could technically choose any seed you'd like.)
* Format the output like in the <span style="color:royalblue">Expected output</span> cell below.
* Should we sample with replacement or without replacement? **Hint:** What happens if a business is selected twice?
* Bonus points for writing the loop in a way that works with any number of columns.

In [241]:
# Seed random seed
np.random.seed(123)

# Print selected businesses from each group
for arr in id_matrix.transpose():
    x = range(1,10)
    art = np.random.choice(arr[x], 5, replace=False)
    print('Group {}: {}'.format(x, art))



Group range(1, 10): [9 2 7 8 5]
Group range(1, 10): [175 177 176 174 179]
Group range(1, 10): [344 343 350 349 342]
Group range(1, 10): [517 513 520 512 518]
Group range(1, 10): [688 684 687 690 686]
Group range(1, 10): [859 856 852 860 854]
Group range(1, 10): [1023 1028 1026 1029 1030]
Group range(1, 10): [1200 1192 1193 1199 1195]
Group range(1, 10): [1363 1369 1370 1362 1364]
Group range(1, 10): [1532 1540 1537 1534 1538]


<strong style="color:RoyalBlue">Expected output:</strong>

<pre>
Group 1: [ 92  73 139  54 147]
Group 2: [182 333 219 292 214]
Group 3: [482 384 400 458 477]
Group 4: [662 603 676 594 609]
Group 5: [827 718 829 845 803]
Group 6: [979 893 932 864 984]
Group 7: [1115 1103 1093 1062 1160]
Group 8: [1308 1248 1231 1222 1330]
Group 9: [1492 1406 1401 1456 1398]
Group 10: [1680 1674 1697 1534 1540]
</pre>

Awesome, now we're ready to start visiting the businesses... Let's start with Group 1 and the business with ID 7. After checking our manual, we find out that this business happens to be flower shop. We'll see why that's relevant in the next lesson.

#### The mission continues in the next lesson...

In this lesson, you narrowed the list of businesses down through stratified random sampling. In the next lesson, you'll visit the flower shop and offer help using your data analysis skills!